namespace Utils;

public static class AttributeStringBuild
{
	/// <summary>
	/// 生成代码的工具名称和版本号。
	/// </summary>
	/// <param name="generator"></param>
	/// <param name="version"></param>
	/// <returns></returns>
	public static string GeneratedCode(string generator, string version) =>
		$"[global::System.CodeDom.Compiler.GeneratedCode(\"{generator}\",\"{version}\")]";


	/// <summary>
	/// 在运行时不收集代码覆盖率信息。
	/// </summary>
	/// <returns></returns>
	public static string ExcludeFromCodeCoverage =>
		"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";


	/// <summary>
	/// 指示编译器应将指定成员的不为 null 断言视为已知。
	/// </summary>
	/// <param name="fieldName"></param>
	/// <returns></returns>
	public static string MemberNotNull(string fieldName) =>
		$"[global::System.Diagnostics.CodeAnalysis.MemberNotNull(\"{fieldName}\")]";


	public static string GeneratedTitle =>
		@"// <auto-generated/>
#pragma warning disable
#nullable enable
";
}