using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;

namespace InfoSet;

public static class Program
{
	private static readonly string _rootPath = Path.Combine(
		Environment.CurrentDirectory,
		"../../../../../"
	);

	public static string GeneratedTitle(string generator, DateTime time)
	{
		return $@"// <auto-generated>
//     Generated by {generator} on {time:yyyy-MM-dd HH:mm:ss}.
// </auto-generated>";
	}

	public static void Main()
	{
		var config = JsonSerializer.Deserialize<InfoConfig>(
			File.ReadAllText(Path.Combine(_rootPath, "Info.json"))
		);
		if (config is null)
			return;
		File.WriteAllText(
			Path.Combine(_rootPath, config.OutputPath),
			BuildInfoConfig(config),
			Encoding.UTF8
		);
	}

	public static string BuildInfoConfig(InfoConfig infoConfig)
	{
		var builder = new StringBuilder();
		builder.AppendLine(GeneratedTitle("InfoConfigGenerator", DateTime.Now));
		if (!string.IsNullOrEmpty(infoConfig.Namespace))
			builder.AppendLine($"namespace {infoConfig.Namespace};");
		builder.AppendLine();
		builder.AppendLine($"public static class {infoConfig.Name} {{");
		foreach (var property in infoConfig.Properties)
			builder.AppendLine(
				$"\t{BuildPropertyInfo(property, infoConfig.Targets)}"
			);
		builder.AppendLine("}");
		return builder.ToString();
	}

	public static string BuildPropertyInfo(
		PropertyInfo propertyInfo,
		Dictionary<string, TargetInfo> targets
	)
	{
		var builder = new StringBuilder();
		if (propertyInfo.Options is not null)
		{
			var options = propertyInfo.Options;
			if (targets.TryGetValue(options.Target, out var target))
			{
				TargetExecutor.Execute(target, _rootPath, propertyInfo.Value);
			}
		}

		builder.Append(
			$"public const {propertyInfo.Type} {propertyInfo.Name} = "
		);
		if (propertyInfo.Type == "string")
			builder.Append($"\"{propertyInfo.Value}\"");
		else
			builder.Append(propertyInfo.Value);
		builder.AppendLine(";");

		return builder.ToString();
	}
}

public static class TargetExecutor
{
	public static void Execute(
		TargetInfo targetInfo,
		string rootPath,
		string value
	)
	{
		switch (targetInfo.Type)
		{
			case "csproj":
				ExecuteCsproj(targetInfo, rootPath, value);
				break;
		}
	}

	public static void ExecuteCsproj(
		TargetInfo targetInfo,
		string rootPath,
		string value
	)
	{
		var filePath = Path.Combine(rootPath, targetInfo.FilePath);
		var xml = XDocument.Parse(File.ReadAllText(filePath));
		XElement? element = xml.Root;
		foreach (var path in targetInfo.Path)
		{
			if (path == "$Value")
				element?.Value = value;
			else
				element = element?.Element(path);
			if (element is null)
				break;
		}
		File.WriteAllText(filePath, xml.ToString(), Encoding.UTF8);
	}
}
