// <auto-generated>
//     Generated by InfoConfigGenerator on 2025-11-11 22:37:18.
// </auto-generated>
namespace Utils;

public static class ProjectInfo {
	public const string Title = "GodotToolkits";

	public const string MvvmVersion = "0.2.5";

	public const string I18NVersion = "1.0.7";

}
